name: Cleanup old Images from ECR

on:
    schedule:
        - cron: '0 12 * * *' #runs at 12:00 UTC everyday

jobs:
    delete_ecr_images:
      name: Check and Delete old images
      runs-on: ubuntu-latest
    
      steps:
      - name: Checkout
        uses: actions/checkout@v2        

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: setup python
        uses: actions/setup-python@v2
        with:
            python-version: '3.7.3' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run sj-gobierno.py to get the latest data        
        run: python deleteImg-ecr_repos.py -l us-east-1 -k ${{ secrets.AWS_ACCESS_KEY_ID }} -s {{ secrets.AWS_SECRET_ACCESS_KEY }} -r econ-github-actions-test
